### ISSUE TITLE
User Feedback on Success/Fail

### ISSUE THREAD

**Issue by ChekTek** [pherting/streamdeck-mqtt#1]
Feature Request: Use showAlert or showOk when the request fails or is successful
https://developer.elgato.com/documentation/stream-deck/sdk/events-sent/#showalert

**Comment by pherting** [comment]
Thanks for your feedback!
I added it in Version 1.2 now. Have fun ;)

https://github.com/pherting/streamdeck-mqtt/releases/tag/V1.2
