### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by daes10** [pherting/streamdeck-mqtt#2]
Thank you so for this plugin. A waited a long time for such a plugin on my streamdeck.

But how I enable websocket on my mosquitto broker?

I tried it, but why the button doesnt work?

I dont find how I can configure my mosquitto to enable websockets.
I heard something about configuration file change, but my broker dont use a file. I think it uses the default.

**Comment by daes10** [comment]
So I had a lot of Problem I now make it happen throught simple http commands.

But I hope you can more describe, how to properly set up the broker for websocket support.

**Comment by pherting** [comment]
Hey @daes10 sorry for the late Answer!

You need to start mosquitto with a config like this:
`mosquitto -c /etc/mosquitto/mosquitto.conf`

In your config you need a second listener for WebSockets like this:
`listener 1883`
`listener 9001`
`protocol websockets`

Hope it is not to late xD

Thanks for the hint that i create a better Readme!

**Comment by daes10** [comment]
@pherting ok thanks for your help! I will try... but not for now. For now it worked with http. But when i have enough time for it, i will try this. You will hear from me.... ;)

**Comment by mzac** [comment]
I was trying to get it working with Home Assistant and the Mosquitto Broker integration.  I had to use port 1884 which is defined in the integration's config:

![image](https://user-images.githubusercontent.com/10270879/150400518-e1bc1ae2-7106-45b2-9a36-a4988753b7ca.png)

**Comment by pherting** [comment]
Thanks @mzac for this screenshot!
This is exactly what i mean, you need to configure Mosquitto do listen also to the other ports with WebSocket enabled and optional over secure SSL.
