### ISSUE TITLE
Retain messages

### ISSUE THREAD

**Issue by yetisnack1** [pherting/streamdeck-mqtt#3]
Is there anyway currently / planned to be able to pass the -r (retain message) flag?  I'm using this plugin to control some arduinos that go into deep sleep mode, so they aren't always awake when messages come in.  If I can pass the retain flag with the message they will catch it when they wake up.  Other than that, this plugin is awesome and thank you so much for providing it.

**Comment by pherting** [comment]
Hey @yetisnack1, thanks for your Message!
That is a very good idea. I will look into it and implement this as soon as possible. I think it needs 2-3 Days do deploy the new version to the StreamDeck Market. So give me feedback when you test it than ;)

**Comment by pherting** [comment]
Hey @yetisnack1, Version 1.3 are released at github now. You can test it here or wait a few Days for the normal update in your StreamDeck Software. Hope you like it and it works like expected. Let me know how it works four you ;)

**Comment by pherting** [comment]
Hey @yetisnack1, that was faster than i expected.. It's also online at StreamDeck Market.. so you can normaly update ;) Have Fun!

**Comment by yetisnack1** [comment]
@pherting Thank you for the quick fix.  I had already installed from GitHub and it is working great.  I have a feeling I'm going to be using this plugin a ton!
