### ISSUE TITLE
No publish

### ISSUE THREAD

**Issue by EB1TR** [pherting/streamdeck-mqtt#5]
Hello.

Thanks for your work!

I have this configuration:
![imagen](https://user-images.githubusercontent.com/21270997/205994586-aa658f56-fc67-44ba-bbb3-2acaf8e240b5.png)

The button no publish anything. Try with mqtt://, without, dash as first character in the topic, without... Any idea?

Thanks in advance!

**Comment by pherting** [comment]
Hello,

please take a look into this issue:
https://github.com/pherting/streamdeck-mqtt/issues/2

I think you have the same problem. You need to use Mqtt over Websockets wirh Port 1884.
So you need to configure your Broker correct.

Let me now if it works for you.

**Comment by EB1TR** [comment]
Thanks for support!

Yes... Now works fine. In debug env can be help the feedback signal, but as option may be better.

Thanks for your work!
