### ISSUE TITLE
I cannot get this to connect/publish by any means.

### ISSUE THREAD

**Issue by FunkyJamma** [pherting/streamdeck-mqtt#6]
I am having an issue where I just get a yellow triangle with an exclamation. I am 100% certain that my settings are correct. I have been able to plublish from other devices with no issues. The logs dont show anything other than the button was pressed.

**Comment by pherting** [comment]
Hello, on wich Port is your Mqtt Broker running? Is it configured with connection over WebSockets?

Please take a look into this Topic:
https://github.com/pherting/streamdeck-mqtt/issues/2

**Comment by FunkyJamma** [comment]
It is on port 1883, I use home assistant. It worked before but one day it just stopped working.

**Comment by pherting** [comment]
The plugin worked normaly before?
Because Port 1883 seems like you are using normal MQTT and not the WebSocket Version!?
You are sure that you are using the WebSocket Protocol in your configuration? Can you share some screenshots from your config?

**Comment by FunkyJamma** [comment]
Yes it worked before and it stopped so i decided to redo my homeassistant install and yes you are right I was using the normal mqtt port instead of 8083. I didnt understand what you were saying at first and it just clicked. Thank you for your help it is working now.

**Comment by pherting** [comment]
You are welcome, that's nice to hear! Have fun with the plugin ;)

**Comment by damdo** [comment]
Thanks for your work @pherting, awesome plugin.
I think it would be worth adding - to the main README page - the fact that one must configure and use MQTT over websockets on the MQTT server side in order to successfully connect to it.
What do you think?
Thanks!
